services:

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

  postfix:
    image: boky/postfix:latest
    expose:
    - "25:25"
    environment:
      - MYNETWORKS=127.0.0.0/8 172.0.0.0/24
      - HOSTNAME=localhost
      - SENDER_DOMAIN=localhost
      - ALLOW_EMPTY_SENDER_DOMAINS=true
    ports:
      - "25:25"
    restart: always
