services:

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"